fix "load more" in network timelines (#5457)
There was an ugly off-by-one bug in the load more logic of network timelines, that caused duplicate posts being shown, which crashed the Compose LazyColumn.

It also had no support for oldest first loading, so I added it.

I also cleaned up the code and added a test to make sure it is now correct.

```
java.lang.IllegalArgumentException: Key "116121960265480193" was already used. If you are using LazyColumn/Row please make sure you provide a unique key for each item.
    	at androidx.compose.ui.internal.InlineClassHelperKt.throwIllegalArgumentException(InlineClassHelper.kt:36)
    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState.subcompose(SubcomposeLayout.kt:1366)
    	at androidx.compose.ui.layout.LayoutNodeSubcompositionsState$Scope.subcompose(SubcomposeLayout.kt:1231)
    	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasureScopeImpl.compose(LazyLayoutMeasureScope.kt:94)
    	at androidx.compose.foundation.lazy.layout.LazyLayoutMeasuredItemProvider.getPlaceables-3p2s80s(LazyLayoutMeasuredItem.kt:60)
    	...

```

Reviewed-on: https://codeberg.org/tusky/Tusky/pulls/5457
Reviewed-by: Tak <tak@noreply.codeberg.org>
Reviewed-by: Martin Marconcini <gryzor@noreply.codeberg.org>
Co-authored-by: Conny Duck <git@connyduck.at>
Co-committed-by: Conny Duck <git@connyduck.at>